name: PIPELINE
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: nesttenancy
  REGISTRY_SERVER: docker.pkg.github.com/refactoring-do/cloud-based-multitenancy-nestjs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ env.AZURE_WEBAPP_NAME }}
          image-tag: ${{github.sha}}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: "${{ env.REGISTRY_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}"

      - uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
                {
                    "name": "DB_HOST",
                    "value": "${{ secrets.DB_HOST }}",
                    "slotSetting": false
                },
                {
                    "name": "DB_PORT",
                    "value": "${{ secrets.DB_PORT }}",
                    "slotSetting": false
                },
                {
                    "name": "DB_USER",
                    "value": "${{ secrets.DB_USER }}",
                    "slotSetting": false
                },
                {
                    "name": "DB_PASSWORD",
                    "value": "${{ secrets.DB_PASSWORD }}",
                    "slotSetting": false
                },
                {
                    "name": "DB_NAME",
                    "value": "${{ secrets.DB_NAME }}",
                    "slotSetting": false
                },
                {
                    "name": "APP_PORT",
                    "value": "${{ secrets.APP_PORT }}",
                    "slotSetting": false
                }
            ]

      - name: Azure logout
        run: |
          az logout
